SELECT * FROM DIM_Device_Type
SELECT * FROM DIM_PAYMENT_METHOD
SELECT * FROM [DIM_TROPHY_INFO] 
SELECT * FROM DIM_USER_INFO
SELECT * FROM DIM_GAME_INFO
SELECT * FROM DIM_DATE
---------------------------------
SELECT * FROM FACT_SALES 
SELECT * FROM FACT_TROPHIES
SELECT * FROM FACT_GAME_PLAY 
---------------------------------
SELECT * FROM Dim_Validation_Log  
