SELECT * FROM [dbo].[ODS_Countries] 
SELECT * FROM [dbo].[ODS_Cities]
SELECT * FROM [dbo].[ODS_States]
SELECT * FROM [dbo].[ODS_User_location]
SELECT * FROM [dbo].[ODS_User_Activity]
SELECT * FROM [dbo].[ODS_User_Contact]
SELECT * FROM [dbo].[ODS_User_Basic]
SELECT * FROM [dbo].[ODS_Game_Genres]
SELECT * FROM [dbo].[ODS_Game_Prices]
SELECT * FROM [dbo].[ODS_Game_Metadata]
SELECT * FROM [dbo].[ODS_Game_Titles]
SELECT * FROM [dbo].[ODS_Game_Sessions]
SELECT * FROM [dbo].[ODS_Orders]
SELECT * FROM [dbo].[ODS_Trophies]

